name: Basic CI Pipeline

# Run the workflow on every push or pull request to the main branch
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

# Define the job
jobs:
  build:
    runs-on: ubuntu-latest  # Use the latest Ubuntu environment for the runner

    steps:
      # Step 1: Checkout the code from the repository
      - name: Checkout code
        uses: actions/checkout@v3

      # Step 2: Run a simple command (e.g., list files as a placeholder for build/test)
      - name: List project files
        run: ls -la
